server:
  port: 8080
spring:
  application:
    name: room-service
  config:
    import: optional:configserver:http://localhost:8888
#------------------ mysql info ---------------------
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/room_reservation
#    username: omid
#    password: omid@1999
