server:
  port: 8083
spring:
  application:
    name: reservation-service
  config:
    import: optional:configserver:http://localhost:8080
  data:
    mongodb:
      host: localhost
      authentication-database: admin
      port: 27017
      database: reservation-service
    redis:
      database: 1
      port: 6379
      host: localhost
